name: Check
on: [push, pull_request]
jobs:
    ktlintCheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v6

            - name: Setup Java
              uses: actions/setup-java@v6
              with:
                  distribution: temurin
                  java-version: '25'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v6

            - name: Run ktlint
              run: ./gradlew ktlintCheck
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v6

            - name: Setup Java
              uses: actions/setup-java@v6
              with:
                  distribution: temurin
                  java-version: '25'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v6

            - name: Test
              run: ./gradlew test
